-- ReadyScore V19.2 — Learning Preference data/runtime activation
-- Depends on 20260927150000_v19_2_learning_preference so the new enum values
-- are committed before they are used below.

UPDATE "TestType" SET "status"='ACTIVE', "runtimeKey"='LEARNING_PREFERENCE', "description"='Customer-facing Learning Preference assessment V19.2 covering Visual, Auditory, and Kinesthetic preferences.' WHERE "code"='LEARNING_PREFERENCE';
INSERT INTO "TestType" ("id","code","name","category","status","description","runtimeKey") VALUES ('test-type-learning-preference','LEARNING_PREFERENCE','Learning Preference Profile','LEARNING','ACTIVE','Customer-facing Learning Preference assessment V19.2 covering Visual, Auditory, and Kinesthetic preferences.','LEARNING_PREFERENCE') ON CONFLICT ("code") DO UPDATE SET "status"='ACTIVE',"runtimeKey"='LEARNING_PREFERENCE';
INSERT INTO "TaxonomyVersion" ("id","testTypeId","version","status","sourceVersion","metadata") VALUES ('taxonomy-learning-preference-v1','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','ACTIVE','V19.2_LEARNING_PREFERENCE','{"instrumentStatus":"MVP","architectureVersion":"V19.2"}') ON CONFLICT ("testTypeId","version") DO NOTHING;
INSERT INTO "TaxonomyNode" ("id","taxonomyId","code","name","nodeType","level") VALUES ('lp-domain-1','taxonomy-learning-preference-v1','VISUAL','Visual','DOMAIN',0) ON CONFLICT ("taxonomyId","code") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-01','LP-01-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-01','LP-01-01','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih mudah memahami materi ketika informasi disajikan dalam diagram atau gambar.','VISUAL','VISUAL_CORE','VISUAL_01','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-02','LP-01-02',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-02','LP-01-02','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya terbantu ketika catatan menggunakan struktur visual seperti tabel atau bagan.','VISUAL','VISUAL_CORE','VISUAL_02','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-03','LP-01-03',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-03','LP-01-03','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya sering membayangkan bentuk atau susunan informasi saat mempelajarinya.','VISUAL','VISUAL_CORE','VISUAL_03','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-04','LP-01-04',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-04','LP-01-04','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Contoh visual membantu saya menangkap konsep yang baru.','VISUAL','VISUAL_CORE','VISUAL_04','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-05','LP-01-05',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-05','LP-01-05','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya nyaman menggunakan warna atau penanda visual untuk mengorganisasi catatan.','VISUAL','VISUAL_CORE','VISUAL_05','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-06','LP-01-06',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-06','LP-01-06','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya cenderung memahami hubungan antar-ide setelah melihat peta konsep.','VISUAL','VISUAL_CORE','VISUAL_06','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-07','LP-01-07',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-07','LP-01-07','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya terbantu dengan demonstrasi yang dapat saya lihat secara langsung.','VISUAL','VISUAL_CORE','VISUAL_07','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-08','LP-01-08',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-08','LP-01-08','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saat belajar, saya suka menyusun informasi agar mudah dipindai secara visual.','VISUAL','VISUAL_CORE','VISUAL_08','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-09','LP-01-09',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-09','LP-01-09','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih cepat mengenali pola ketika informasi ditampilkan secara visual.','VISUAL','VISUAL_CORE','VISUAL_09','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-01-10','LP-01-10',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-01-10','LP-01-10','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya menikmati materi belajar yang memiliki ilustrasi atau representasi visual yang jelas.','VISUAL','VISUAL_CORE','VISUAL_10','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "TaxonomyNode" ("id","taxonomyId","code","name","nodeType","level") VALUES ('lp-domain-2','taxonomy-learning-preference-v1','AUDITORY','Auditory','DOMAIN',0) ON CONFLICT ("taxonomyId","code") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-01','LP-02-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-01','LP-02-01','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih mudah memahami materi setelah mendengar penjelasan yang runtut.','AUDITORY','AUDITORY_CORE','AUDITORY_01','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-02','LP-02-02',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-02','LP-02-02','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Diskusi membantu saya memperjelas pemahaman terhadap suatu konsep.','AUDITORY','AUDITORY_CORE','AUDITORY_02','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-03','LP-02-03',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-03','LP-02-03','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya sering mengingat informasi melalui kalimat atau penjelasan yang saya dengar.','AUDITORY','AUDITORY_CORE','AUDITORY_03','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-04','LP-02-04',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-04','LP-02-04','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya terbantu ketika dapat menjelaskan kembali materi dengan berbicara.','AUDITORY','AUDITORY_CORE','AUDITORY_04','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-05','LP-02-05',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-05','LP-02-05','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Percakapan tentang suatu topik membuat saya menemukan pemahaman baru.','AUDITORY','AUDITORY_CORE','AUDITORY_05','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-06','LP-02-06',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-06','LP-02-06','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya nyaman mengikuti pembelajaran yang banyak menggunakan penjelasan verbal.','AUDITORY','AUDITORY_CORE','AUDITORY_06','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-07','LP-02-07',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-07','LP-02-07','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya suka mendengarkan contoh atau cerita untuk memahami suatu gagasan.','AUDITORY','AUDITORY_CORE','AUDITORY_07','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-08','LP-02-08',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-08','LP-02-08','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya sering mengulang materi dengan mengucapkannya atau menjelaskannya kepada orang lain.','AUDITORY','AUDITORY_CORE','AUDITORY_08','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-09','LP-02-09',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-09','LP-02-09','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih mudah mengikuti langkah belajar ketika instruksinya dijelaskan secara lisan.','AUDITORY','AUDITORY_CORE','AUDITORY_09','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-02-10','LP-02-10',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-02-10','LP-02-10','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya menikmati sesi belajar yang memberi ruang untuk bertanya dan berdiskusi.','AUDITORY','AUDITORY_CORE','AUDITORY_10','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "TaxonomyNode" ("id","taxonomyId","code","name","nodeType","level") VALUES ('lp-domain-3','taxonomy-learning-preference-v1','KINESTHETIC','Kinesthetic','DOMAIN',0) ON CONFLICT ("taxonomyId","code") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-01','LP-03-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-01','LP-03-01','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih mudah memahami materi setelah mencoba atau mempraktikkannya.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_01','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-02','LP-03-02',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-02','LP-03-02','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya terbantu ketika pembelajaran melibatkan simulasi atau latihan langsung.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_02','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-03','LP-03-03',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-03','LP-03-03','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya suka mempelajari sesuatu dengan melakukan percobaan sendiri.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_03','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-04','LP-03-04',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-04','LP-03-04','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya memahami konsep dengan lebih baik ketika dapat berinteraksi langsung dengan objek atau alat.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_04','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-05','LP-03-05',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-05','LP-03-05','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya cenderung belajar sambil mencoba langkah demi langkah.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_05','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-06','LP-03-06',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-06','LP-03-06','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Latihan praktis membantu saya mengingat materi lebih lama.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_06','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-07','LP-03-07',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-07','LP-03-07','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya menikmati pembelajaran yang membuat saya aktif melakukan sesuatu.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_07','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-08','LP-03-08',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-08','LP-03-08','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya lebih mudah memahami prosedur setelah mempraktikkannya sendiri.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_08','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-09','LP-03-09',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-09','LP-03-09','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya terbantu ketika dapat menggunakan contoh nyata untuk mencoba sebuah konsep.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_09','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "Question" ("id","code","createdAt","updatedAt") VALUES ('LP-03-10','LP-03-10',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionVersion" ("id","questionId","testTypeId","taxonomyVersion","version","text","domain","subdomain","indicator","type","answerType","reverseScore","weight","scale","scoringKey","difficulty","status","mappingStatus","sourceFile","createdAt","updatedAt") VALUES ('lp-qv-03-10','LP-03-10','test-type-learning-preference','LEARNING_PREFERENCE_TAXONOMY_V1','v1','Saya suka mengubah penjelasan menjadi aktivitas atau latihan yang dapat langsung dilakukan.','KINESTHETIC','KINESTHETIC_CORE','KINESTHETIC_10','PREFERENCE','LIKERT_5',false,1,'{1,2,3,4,5}','{1,2,3,4,5}','MEDIUM','PUBLISHED','APPROVED','V19.2_LEARNING_PREFERENCE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("questionId","version") DO NOTHING;
INSERT INTO "AssessmentConfiguration" ("id","assessmentType","code","name","description","updatedAt") VALUES ('learning-preference-v1','LEARNING_PREFERENCE','learning-preference-v1','Learning Preference Assessment','V19.2 Learning Preference configuration',CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "AssessmentConfigurationVersion" ("id","configurationId","version","questionBankVersion","taxonomyVersion","scoringVersion","selectionAlgorithmVersion","questionCount","status","updatedAt") VALUES ('learning-preference-v1-version','learning-preference-v1','LEARNING_PREFERENCE_CONFIG_V1','LEARNING_PREFERENCE_QB_V1','LEARNING_PREFERENCE_TAXONOMY_V1','LEARNING_PREFERENCE_SCORE_V1','LEARNING_PREFERENCE_SELECTION_V1',30,'ACTIVE',CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "QuestionPackage" ("id","testTypeId","code","name","description") VALUES ('learning-preference-runtime-package','test-type-learning-preference','learning-preference-runtime','LEARNING_PREFERENCE Internal Runtime Package','Internal runtime package for V19.2 Learning Preference.') ON CONFLICT ("code") DO NOTHING;
INSERT INTO "QuestionPackageVersion" ("id","packageId","version","totalQuestions","timeLimitSeconds","taxonomyVersionId","status","metadata") VALUES ('learning-preference-runtime-version','learning-preference-runtime-package','v1',30,1200,'taxonomy-learning-preference-v1','PUBLISHED','{"internalRuntime":true,"configurationVersionId":"learning-preference-v1-version","questionBankVersion":"LEARNING_PREFERENCE_QB_V1","selectionScope":"TEST_TYPE","selectionAlgorithmVersion":"LEARNING_PREFERENCE_SELECTION_V1"}') ON CONFLICT ("id") DO NOTHING;
UPDATE "AssessmentConfigurationVersion" SET "questionPackageVersionId"='learning-preference-runtime-version' WHERE "id"='learning-preference-v1-version';
INSERT INTO "QuestionPackageCompositionRule" ("id","packageVersionId","taxonomyNodeId","requiredCount") VALUES ('lp-rule-1','learning-preference-runtime-version','lp-domain-1',10) ON CONFLICT ("packageVersionId","taxonomyNodeId") DO NOTHING;
INSERT INTO "QuestionPackageCompositionRule" ("id","packageVersionId","taxonomyNodeId","requiredCount") VALUES ('lp-rule-2','learning-preference-runtime-version','lp-domain-2',10) ON CONFLICT ("packageVersionId","taxonomyNodeId") DO NOTHING;
INSERT INTO "QuestionPackageCompositionRule" ("id","packageVersionId","taxonomyNodeId","requiredCount") VALUES ('lp-rule-3','learning-preference-runtime-version','lp-domain-3',10) ON CONFLICT ("packageVersionId","taxonomyNodeId") DO NOTHING;

INSERT INTO "ProductEntitlement" ("id","productId","type","resourceType","resourceKey","metadata") VALUES
('v19-2-medium-test-learning-preference','product-medium','TEST_ACCESS','TEST_TYPE','LEARNING_PREFERENCE','{"version":"V19.2","source":"LEARNING_PREFERENCE_BUNDLE_EXPANSION","includedIn":"MEDIUM"}'),
('v19-2-medium-result-learning-preference','product-medium','RESULT_ACCESS','TEST_TYPE','LEARNING_PREFERENCE','{"version":"V19.2","source":"LEARNING_PREFERENCE_BUNDLE_EXPANSION","includedIn":"MEDIUM"}'),
('v19-2-advance-test-learning-preference','product-advance','TEST_ACCESS','TEST_TYPE','LEARNING_PREFERENCE','{"version":"V19.2","source":"LEARNING_PREFERENCE_BUNDLE_EXPANSION","includedIn":"ADVANCE"}'),
('v19-2-advance-result-learning-preference','product-advance','RESULT_ACCESS','TEST_TYPE','LEARNING_PREFERENCE','{"version":"V19.2","source":"LEARNING_PREFERENCE_BUNDLE_EXPANSION","includedIn":"ADVANCE"}')
ON CONFLICT ("productId","type","resourceType","resourceKey") DO UPDATE SET "metadata"=EXCLUDED."metadata";

WITH active_bundle AS (
  SELECT DISTINCT ON (ue."userId") ue."userId", ue."productId", ue."sourceOrderId", ue."startsAt", ue."endsAt" FROM "UserEntitlement" ue WHERE ue."productId" IN ('product-medium','product-advance') AND ue."status"='ACTIVE' AND ue."startsAt" <= CURRENT_TIMESTAMP AND (ue."endsAt" IS NULL OR ue."endsAt" > CURRENT_TIMESTAMP) ORDER BY ue."userId", CASE WHEN ue."productId"='product-advance' THEN 2 ELSE 1 END DESC, ue."updatedAt" DESC
)
INSERT INTO "UserEntitlement" ("id","userId","productId","type","resourceType","resourceKey","status","source","sourceOrderId","usageLimit","usageConsumed","startsAt","endsAt")
SELECT concat('v19lp_',substr(md5(ab."userId" || ':' || x."type" || ':' || x."resourceKey"),1,24)), ab."userId",ab."productId",x."type",'TEST_TYPE',x."resourceKey",'ACTIVE','V19.2_LEARNING_PREFERENCE_BACKFILL',ab."sourceOrderId",1,0,ab."startsAt",ab."endsAt" FROM active_bundle ab CROSS JOIN (VALUES ('TEST_ACCESS'::"EntitlementType",'LEARNING_PREFERENCE'),('RESULT_ACCESS'::"EntitlementType",'LEARNING_PREFERENCE')) x("type","resourceKey") WHERE NOT EXISTS (SELECT 1 FROM "UserEntitlement" existing WHERE existing."userId"=ab."userId" AND existing."type"=x."type" AND existing."resourceType"='TEST_TYPE' AND existing."resourceKey"=x."resourceKey") ON CONFLICT ("userId","type","resourceType","resourceKey") DO NOTHING;
UPDATE "Product" SET "description"='IQ + EQ + DISC + RIASEC + Work Attitude + Learning Preference with the initial assessment entitlement for each.' WHERE "id"='product-medium';
UPDATE "Product" SET "description"='All available assessment types including Work Attitude and Learning Preference, plus Cross-Test Profiling and the personalized V15 report.' WHERE "id"='product-advance';
