import { NextResponse } from "next/server";
import { evaluateQuestionPackageProductionEligibility, listProductionEligibility } from "../../../../lib/question-package-eligibility";
import { requireAdminApi } from "../../../../lib/auth/admin";
import { archiveQuestionPackageVersion, createQuestionPackage, createQuestionPackageVersion, getQuestionPackage, getQuestionPackageCatalog, listQuestionPackages, publishQuestionPackageVersion, validateQuestionPackageVersion } from "../../../../lib/question-package-repository";
export const runtime="nodejs"; export const dynamic="force-dynamic";
function failResponse(error:unknown){const code=error instanceof Error?error.message:"INTERNAL_ERROR";const nf=["PACKAGE_NOT_FOUND","PACKAGE_VERSION_NOT_FOUND","TEST_TYPE_NOT_FOUND","TAXONOMY_NOT_FOUND","COMPOSITION_NODE_NOT_FOUND"];const status=code==="UNAUTHENTICATED"?401:code==="FORBIDDEN"?403:nf.includes(code)?404:422;return NextResponse.json({ok:false,error:{code,message:"Question package action failed."}},{status});}
function parseRules(value:unknown){if(!Array.isArray(value))throw new Error("COMPOSITION_REQUIRED");return value.map(item=>{if(!item||typeof item!=="object")throw new Error("INVALID_COMPOSITION_RULE");const row=item as Record<string,unknown>;return {taxonomyNodeId:String(row.taxonomyNodeId??"").trim(),requiredCount:Number(row.requiredCount)};});}
export async function GET(request:Request){try{await requireAdminApi();const p=new URL(request.url).searchParams;if(p.get("catalog")==="1")return NextResponse.json({ok:true,catalog:await getQuestionPackageCatalog()});if(p.get("eligibility")==="1"){const versionId=p.get("versionId");return NextResponse.json({ok:true,eligibility:versionId?await evaluateQuestionPackageProductionEligibility(versionId):await listProductionEligibility()});}const id=p.get("id");if(id){const item=await getQuestionPackage(id);if(!item)return NextResponse.json({ok:false,error:{code:"PACKAGE_NOT_FOUND"}},{status:404});return NextResponse.json({ok:true,package:item});}return NextResponse.json({ok:true,packages:await listQuestionPackages()});}catch(e){return failResponse(e);}}
export async function POST(request:Request){try{const actor=await requireAdminApi();const body=await request.json() as Record<string,unknown>;const action=String(body.action??"");if(action==="VALIDATE")return NextResponse.json({ok:true,validation:await validateQuestionPackageVersion(String(body.versionId??""))});if(action==="PUBLISH")return NextResponse.json({ok:true,version:await publishQuestionPackageVersion(String(body.versionId??""),actor.id)});if(action==="ARCHIVE")return NextResponse.json({ok:true,version:await archiveQuestionPackageVersion(String(body.versionId??""),actor.id)});const input={totalQuestions:Number(body.totalQuestions),timeLimitSeconds:Number(body.timeLimitSeconds),taxonomyVersionId:body.taxonomyVersionId==null||body.taxonomyVersionId===""?null:String(body.taxonomyVersionId),compositionRules:parseRules(body.compositionRules)};if(action==="CREATE"){const created=await createQuestionPackage({id:body.id==null||body.id===""?undefined:String(body.id),testTypeId:String(body.testTypeId??""),code:String(body.code??""),name:String(body.name??""),description:body.description==null?null:String(body.description),version:body.version==null||body.version===""?undefined:String(body.version),...input},actor.id);return NextResponse.json({ok:true,created},{status:201});}if(action==="NEW_VERSION"){const version=await createQuestionPackageVersion(String(body.packageId??""),input,actor.id);return NextResponse.json({ok:true,version},{status:201});}throw new Error("INVALID_ACTION");}catch(e){return failResponse(e);}}
