import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";
import type { AssessmentReportV19_3 } from "./v19-3-engine";

const CANDIDATES = ["/usr/bin/chromium", "/usr/bin/chromium-browser", "/usr/bin/google-chrome", "/usr/bin/google-chrome-stable", "/opt/homebrew/bin/chromium", "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "/Applications/Chromium.app/Contents/MacOS/Chromium", "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge"];
const esc = (v: string) => v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;");
async function browser() { for (const p of [...(process.env.READYSCORE_CHROMIUM_PATH ? [process.env.READYSCORE_CHROMIUM_PATH] : []), ...(process.env.CHROME_BIN ? [process.env.CHROME_BIN] : []), ...CANDIDATES]) { try { await access(p, fsConstants.X_OK); return p; } catch {} } throw new Error("PDF_RENDERER_NOT_FOUND: Set READYSCORE_CHROMIUM_PATH or CHROME_BIN."); }
async function run(command: string, args: string[]) { await new Promise<void>((resolve, reject) => { const child = spawn(command, args, { stdio: ["ignore", "ignore", "pipe"] }); let stderr = ""; child.stderr.on("data", c => { stderr += c.toString(); }); child.on("error", e => reject(new Error(`PDF_RENDER_PROCESS_ERROR:${e.message}`))); child.on("close", code => code === 0 ? resolve() : reject(new Error(`PDF_RENDER_FAILED:${code}:${stderr.slice(-1000)}`))); }); }
export function isValidV19_3Pdf(pdf: Buffer | Uint8Array | null | undefined) { return !!pdf && pdf.length > 1000 && Buffer.from(pdf).subarray(0, 5).toString() === "%PDF-"; }
export async function renderAssessmentReportPdfV19_3(report: AssessmentReportV19_3) {
  const dir = await mkdtemp(join(tmpdir(), "readyscore-v19-3-report-")); const html = join(dir, "report.html"); const pdfPath = join(dir, "report.pdf");
  const dims = report.dimensions.map(d => `<tr><td>${esc(d.label)}</td><td>${d.score === null ? "—" : String(d.score)}</td><td>${esc(d.description)}</td></tr>`).join("");
  const recs = report.recommendations.map(x => `<li>${esc(x)}</li>`).join("");
  const limits = report.limitations.map(x => `<li>${esc(x)}</li>`).join("");
  const strengths = report.assessmentSummary.strengths.map(x => `<li>${esc(x)}</li>`).join("");
  const areas = report.assessmentSummary.areasToWatch.map(x => `<li>${esc(x)}</li>`).join("");
  const htmlDoc = `<!doctype html><html lang="id"><head><meta charset="utf-8"><style>@page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#0f172a;line-height:1.55}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#4f46e5}.title{font-size:28px;font-weight:800;margin:8px 0 20px}.card{border:1px solid #e2e8f0;border-radius:14px;padding:16px;margin:14px 0}.summary{background:#eef2ff;border-color:#c7d2fe}.identity{background:#f8fafc}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #e2e8f0;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#64748b}h2{font-size:18px;margin-top:24px}li{margin:7px 0}.footer{margin-top:28px;font-size:10px;color:#64748b}</style></head><body><div class="eyebrow">ReadyScore · V19.3 Report Adjustment</div><div class="title">${esc(report.title)}</div><div class="card identity"><b>Peserta</b><p>${esc(report.participantName)}</p><b>Account Owner</b><p>${esc(report.accountOwnerName)}</p></div><div class="card summary"><b>${esc(report.assessmentSummary.title)}</b><p>${esc(report.assessmentSummary.reading)}</p></div><h2>Strengths</h2><div class="card"><ul>${strengths}</ul></div><h2>Areas to Watch</h2><div class="card"><ul>${areas}</ul></div><h2>Interpretasi</h2><div class="card"><p>${esc(report.interpretation.summary)}</p><b>Status:</b> ${esc(report.interpretation.status)} &nbsp; <b>Confidence:</b> ${esc(report.interpretation.confidence)}</div><h2>Visualization Data</h2><div class="card"><table><thead><tr><th>Dimension</th><th>Score</th><th>Meaning</th></tr></thead><tbody>${dims}</tbody></table></div><h2>Recommendation / Exploration</h2><div class="card"><ul>${recs}</ul></div><h2>Interpretation Boundary</h2><div class="card"><ul>${limits}</ul></div><div class="footer">Attempt ${esc(report.attemptId)} · Contract ${esc(report.contractVersion)} · Engine ${esc(report.engineVersion)}</div></body></html>`;
  try { await writeFile(html, htmlDoc, "utf8"); const b = await browser(); await run(b, ["--headless=new", "--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage", `--print-to-pdf=${pdfPath}`, "--no-pdf-header-footer", `file://${html}`]); const pdf = await readFile(pdfPath); if (!isValidV19_3Pdf(pdf)) throw new Error("PDF_OUTPUT_INVALID"); return pdf; } finally { await rm(dir, { recursive: true, force: true }).catch(() => {}); }
}
