"use client";
import { useMemo, useState } from "react";

type Item={questionId:string;questionVersionId:string;code:string;version:string;testTypeCode:string|null;testTypeName:string|null;text:string;domain:string;subdomain:string|null;indicator:string|null;status:string;mappingStatus:string;validationErrors:string[];updatedAt:string;createdAt:string};
type Stats={total:number;draft:number;validated:number;review:number;approved:number;published:number;invalid:number};

const flow=[["DRAFT","VALIDATED"],["VALIDATED","REVIEW_REQUIRED"],["REVIEW_REQUIRED","APPROVED"],["APPROVED","PUBLISHED"],["PUBLISHED","ACTIVE"],["ACTIVE","ARCHIVED"]];
const actions:Record<string,string[]>={DRAFT:["VALIDATE"],VALIDATED:["SUBMIT_REVIEW"],REVIEW_REQUIRED:["APPROVE"],APPROVED:["PUBLISH","ARCHIVE"],PUBLISHED:["ACTIVATE","ARCHIVE"]};

export default function AdminReviewContentOperations({initialItems,initialStats}:{initialItems:Item[];initialStats:Stats}){
 const [items,setItems]=useState(initialItems),[stats,setStats]=useState(initialStats),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[selected,setSelected]=useState<Item|null>(null),[inspected,setInspected]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const visible=useMemo(()=>items.filter(i=>(filter==="ALL"||i.status===filter)&&(!search||`${i.code} ${i.text} ${i.domain} ${i.testTypeCode??""}`.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);
 async function refresh(){const r=await fetch("/api/admin/review",{cache:"no-store"});const j=await r.json();if(j.ok){setItems(j.items);setStats(j.stats)}}
 async function inspect(id:string){const r=await fetch(`/api/admin/review?questionId=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(j.ok){setInspected(j.item);setSelected(items.find(x=>x.questionId===id)||null)}}
 async function act(action:string,id:string){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,questionId:id})});const j=await r.json();if(!r.ok)throw new Error(j.error?.code||"Action failed");setMessage(`${action.replace("_"," ")} complete.`);await refresh();await inspect(id)}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 return <div className="space-y-6">
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><b>Controlled publishing.</b> Review operations validate content and metadata, detect duplicates, require approved mapping before approval/publish, preserve historical versions, and record material actions in an immutable audit trail.</div>
  <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{[["Total",stats.total],["Draft",stats.draft],["Validated",stats.validated],["Review",stats.review],["Approved",stats.approved],["Published",stats.published],["Needs attention",stats.invalid]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs font-bold text-slate-500">{l}</div><div className="mt-1 text-2xl font-black">{v}</div></div>)}</div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm">
   <div className="flex flex-wrap gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code, content, test..." className="min-w-[260px] flex-1 rounded-xl border px-4 py-2.5 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option>ALL</option>{["DRAFT","VALIDATED","REVIEW_REQUIRED","APPROVED","PUBLISHED"].map(s=><option key={s}>{s}</option>)}</select></div>
   <div className="mt-4 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Content</th><th className="px-4 py-3">Test</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Lifecycle</th><th className="px-4 py-3">Validation</th><th className="px-4 py-3">Actions</th></tr></thead>
   <tbody className="divide-y">{visible.map(i=><tr key={i.questionVersionId} className="hover:bg-slate-50"><td className="px-4 py-4"><b>{i.code}</b><div className="mt-1 max-w-md text-xs text-slate-600">{i.text}</div></td><td className="px-4 py-4 font-bold">{i.testTypeCode}</td><td className="px-4 py-4 font-mono text-xs">{i.version}</td><td className="px-4 py-4"><span className="rounded-full border px-2.5 py-1 text-xs font-bold">{i.status}</span>{i.status==="PUBLISHED"&&<div className="mt-1 text-[11px] text-slate-500">runtime active</div>}</td><td className="px-4 py-4">{i.validationErrors.length?<span className="font-bold text-rose-600">{i.validationErrors.length} issue(s)</span>:<span className="font-bold text-emerald-700">Valid</span>}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>inspect(i.questionId)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Inspect</button>{(actions[i.status]||[]).map(a=><button disabled={busy} key={a} onClick={()=>act(a,i.questionId)} className="rounded-lg bg-slate-950 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-50">{a.replace("_"," ")}</button>)}</div></td></tr>)}</tbody></table></div>
   {message&&<div className="mt-4 rounded-xl border bg-slate-50 p-3 text-sm font-bold">{message}</div>}
  </div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Lifecycle control</h2><div className="mt-4 flex flex-wrap items-center gap-2 text-xs font-bold">{flow.map(([a,b],n)=><span key={a} className="flex items-center gap-2"><span className="rounded-full border px-3 py-1.5">{a}</span><span>→</span>{n===flow.length-1?<span className="rounded-full border px-3 py-1.5">{b}</span>:null}</span>)}</div><p className="mt-3 text-xs text-slate-500">The existing runtime represents production-active question content with QuestionStatus.PUBLISHED. L17 preserves that frozen runtime contract and records the operational activation as an audit event.</p></div>
  {selected&&inspected&&<div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="text-lg font-black">Content inspector</h2><p className="text-sm text-slate-500">{inspected.current.code} · {inspected.current.version}</p></div><button onClick={()=>{setSelected(null);setInspected(null)}} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Close</button></div><div className="mt-4 grid gap-4 md:grid-cols-3"><div><div className="text-xs font-bold text-slate-500">Status</div><div className="mt-1 font-bold">{inspected.current.status}</div></div><div><div className="text-xs font-bold text-slate-500">Mapping</div><div className="mt-1 font-bold">{inspected.current.mappingStatus}</div></div><div><div className="text-xs font-bold text-slate-500">Validation</div><div className="mt-1 font-bold">{inspected.validationErrors.length?"Blocked":"Ready"}</div></div></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">{inspected.current.text}</p><h3 className="mt-5 font-black">Version history</h3><div className="mt-2 space-y-2">{inspected.versions.map((v:any)=><div key={v.id} className="flex justify-between rounded-xl border p-3 text-xs"><span className="font-mono">{v.version}</span><span>{v.status}</span><span>{new Date(v.updatedAt).toLocaleString()}</span></div>)}</div><h3 className="mt-5 font-black">Audit trail</h3><div className="mt-2 space-y-2">{inspected.audits.map((a:any)=><div key={a.id} className="rounded-xl border p-3 text-xs"><b>{a.action}</b> · {a.fromStatus||"—"} → {a.toStatus||"—"} · {new Date(a.createdAt).toLocaleString()}</div>)}</div></div>}
 </div>
}
