"use client";
import { useState } from "react";
import { AdminPagination, type AdminPaginationPageSize } from "./AdminPagination";

type Item={questionId:string;questionVersionId:string;code:string;version:string;testTypeCode:string|null;testTypeName:string|null;text:string;domain:string;subdomain:string|null;indicator:string|null;status:string;mappingStatus:string;validationErrors:string[];updatedAt:string;createdAt:string;taxonomyNodeCode:string|null;taxonomyNodeName:string|null;taxonomyNodeType:string|null};
type Stats={total:number;draft:number;validated:number;review:number;approved:number;published:number;invalid:number};
type Pagination={page:number;pageSize:number;totalItems:number;totalPages:number;hasNextPage:boolean;hasPreviousPage:boolean};

const flow=[["DRAFT","VALIDATED"],["VALIDATED","REVIEW_REQUIRED"],["REVIEW_REQUIRED","APPROVED"],["APPROVED","PUBLISHED"],["PUBLISHED","ACTIVE"],["ACTIVE","ARCHIVED"]];
const actions:Record<string,string[]>={DRAFT:["VALIDATE"],VALIDATED:["SUBMIT_REVIEW"],REVIEW_REQUIRED:["APPROVE_MAPPING","APPROVE"],APPROVED:["PUBLISH"],PUBLISHED:["ACTIVATE"]};

export default function AdminReviewContentOperations({initialItems,initialPagination,initialStats}:{initialItems:Item[];initialPagination:Pagination;initialStats:Stats}){
 const [items,setItems]=useState(initialItems),[pagination,setPagination]=useState(initialPagination),[stats,setStats]=useState(initialStats),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[selected,setSelected]=useState<Item|null>(null),[inspected,setInspected]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[selectedIds,setSelectedIds]=useState<Set<string>>(new Set());
 async function inspect(id:string){const r=await fetch(`/api/admin/review?questionId=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(j.ok){setInspected(j.item);setSelected(items.find(x=>x.questionId===id)||null)}}
 async function act(action:string,id:string){setBusy(true);setMessage("");try{let confirmed=false;if(["PUBLISH","ACTIVATE","ARCHIVE"].includes(action)){const preview=await fetch(`/api/admin/review?questionId=${encodeURIComponent(id)}&impactAction=${encodeURIComponent(action)}`,{cache:"no-store"}).then(r=>r.json());if(!preview.ok)throw new Error(preview.error?.code||"Impact preview failed");const blocked=preview.impact?.blocked||[];if(blocked.length)throw new Error(`REVIEW_ACTION_BLOCKED:${blocked.join(",")}`);confirmed=window.confirm(`${action.replace("_"," ")}\n\nHistorical impact: ${preview.impact.historicalImpact}\nFuture customer impact: ${preview.impact.futureCustomerImpact}\nScoring impact: ${preview.impact.scoringImpact}\n\nThis action requires confirmation and may require regression. Continue?`);if(!confirmed){setMessage("Action cancelled.");return;}}const r=await fetch("/api/admin/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,questionId:id,confirmed})});const j=await r.json();if(!r.ok)throw new Error(j.error?.code||"Action failed");setMessage(`${action.replace("_"," ")} complete.`);await refresh();await inspect(id)}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 async function refresh(nextPage=1,nextPageSize=pagination.pageSize,nextSearch=search,nextFilter=filter){setLoading(true);try{const params=new URLSearchParams({page:String(nextPage),pageSize:String(nextPageSize)});if(nextSearch.trim())params.set("search",nextSearch.trim());if(nextFilter!=="ALL")params.set("status",nextFilter);const r=await fetch(`/api/admin/review?${params.toString()}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error?.code||"Review load failed");setItems(j.items);setPagination(j.pagination);setStats(j.stats);setSelectedIds(new Set())}catch(e){setMessage(e instanceof Error?e.message:"Review load failed")}finally{setLoading(false)}}
 async function selectAllMatching(){setBusy(true);setMessage("");try{const params=new URLSearchParams({bulk:"1"});if(search.trim())params.set("search",search.trim());if(filter!=="ALL")params.set("status",filter);const r=await fetch(`/api/admin/review?${params.toString()}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error?.code||"Selection load failed");setSelectedIds(new Set(j.questionIds));setMessage(`${j.total} matching question(s) selected.`)}catch(e){setMessage(e instanceof Error?e.message:"Selection load failed")}finally{setBusy(false)}}
 function toggle(id:string){setSelectedIds(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 function togglePage(){const ids=items.map(i=>i.questionId);const all=ids.length>0&&ids.every(id=>selectedIds.has(id));setSelectedIds(prev=>{const next=new Set(prev);if(all)ids.forEach(id=>next.delete(id));else ids.forEach(id=>next.add(id));return next})}
 async function bulkToPublished(){if(!selectedIds.size){setMessage("Select at least one question first.");return}const count=selectedIds.size;const confirmed=window.confirm(`PROCESS ${count} QUESTION(S) TO PUBLISHED\n\nThe server will advance each selected question through its existing governed lifecycle: VALIDATE → REVIEW → MAPPING APPROVAL → APPROVE → PUBLISH as applicable.\n\nEach mutation remains individually validated and audited. Duplicate or invalid content will remain blocked.\n\nContinue?`);if(!confirmed)return;setBusy(true);setMessage(`Processing ${count} question(s)...`);try{const r=await fetch("/api/admin/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"BULK_TO_PUBLISHED",questionIds:[...selectedIds],confirmed:true})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error?.code||"Bulk lifecycle failed");const result=j.result;const failed=result.failed;setMessage(`Bulk lifecycle complete: ${result.published}/${result.requested} published${failed?`; ${failed} failed — inspect the failed items.`:"."}`);await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Bulk lifecycle failed")}finally{setBusy(false)}}
 function setFilterAndReset(value:string){setFilter(value);refresh(1,pagination.pageSize,search,value)}
 function setSearchAndReset(value:string){setSearch(value);refresh(1,pagination.pageSize,value,filter)}
 function changePage(page:number){refresh(page,pagination.pageSize)}
 function changePageSize(pageSize:AdminPaginationPageSize){refresh(1,pageSize)}
 const pageAllSelected=items.length>0&&items.every(i=>selectedIds.has(i.questionId));
 return <div className="space-y-6">
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><b>Controlled publishing.</b> Review operations validate content and metadata, detect duplicates, require approved mapping before approval/publish, preserve historical versions, and record material actions in an immutable audit trail.</div>
  <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{[["Total",stats.total],["Draft",stats.draft],["Validated",stats.validated],["Review",stats.review],["Approved",stats.approved],["Published",stats.published],["Needs attention",stats.invalid]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs font-bold text-slate-500">{l}</div><div className="mt-1 text-2xl font-black">{v}</div></div>)}</div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm">
   <div className="flex flex-wrap gap-3"><input value={search} onChange={e=>setSearchAndReset(e.target.value)} placeholder="Search code, content, test..." className="min-w-[260px] flex-1 rounded-xl border px-4 py-2.5 text-sm"/><select value={filter} onChange={e=>setFilterAndReset(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option>ALL</option>{["DRAFT","VALIDATED","REVIEW_REQUIRED","APPROVED","PUBLISHED"].map(s=><option key={s}>{s}</option>)}</select></div>
   <div className="mt-4 flex flex-wrap items-center gap-2 rounded-2xl border bg-slate-50 p-3">
    <button disabled={busy||loading} onClick={selectAllMatching} className="rounded-lg border bg-white px-3 py-2 text-xs font-black disabled:opacity-50">Select all matching</button>
    <button disabled={busy||loading||!selectedIds.size} onClick={bulkToPublished} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-40">Process selected → Published</button>
    <button disabled={busy||loading||!selectedIds.size} onClick={()=>setSelectedIds(new Set())} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold disabled:opacity-50">Clear selection</button>
    <span className="ml-auto text-xs font-bold text-slate-600">{selectedIds.size} selected</span>
   </div>
   <div className="mt-4 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="w-12 px-4 py-3"><input type="checkbox" aria-label="Select page" checked={pageAllSelected} onChange={togglePage} disabled={busy||loading||!items.length}/></th><th className="px-4 py-3">Content</th><th className="px-4 py-3">Test</th><th className="px-4 py-3">Taxonomy Node</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Lifecycle</th><th className="px-4 py-3">Validation</th><th className="px-4 py-3">Actions</th></tr></thead>
   <tbody className="divide-y">{items.map(i=><tr key={i.questionVersionId} className="hover:bg-slate-50"><td className="px-4 py-4 align-top"><input type="checkbox" aria-label={`Select ${i.code}`} checked={selectedIds.has(i.questionId)} onChange={()=>toggle(i.questionId)} disabled={busy||loading}/></td><td className="px-4 py-4"><b>{i.code}</b><div className="mt-1 max-w-md text-xs text-slate-600">{i.text}</div></td><td className="px-4 py-4 font-bold">{i.testTypeCode}</td><td className="px-4 py-4 text-xs"><b>{i.taxonomyNodeCode??"—"}</b><div className="mt-1 text-[11px] text-slate-500">{i.taxonomyNodeName??"No taxonomy node resolved"}</div></td><td className="px-4 py-4 font-mono text-xs">{i.version}</td><td className="px-4 py-4"><span className="rounded-full border px-2.5 py-1 text-xs font-bold">{i.status}</span>{i.status==="PUBLISHED"&&<div className="mt-1 text-[11px] text-slate-500">runtime active</div>}</td><td className="px-4 py-4">{i.validationErrors.length?<span className="font-bold text-rose-600">{i.validationErrors.length} issue(s)</span>:<span className="font-bold text-emerald-700">Valid</span>}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>inspect(i.questionId)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Inspect</button>{(actions[i.status]||[]).map(a=><button disabled={busy} key={a} onClick={()=>act(a,i.questionId)} className="rounded-lg bg-slate-950 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-50">{a.replace("_"," ")}</button>)}</div></td></tr>)}</tbody></table></div><div className="mt-4"><AdminPagination page={pagination.page} pageSize={pagination.pageSize} totalItems={pagination.totalItems} totalPages={pagination.totalPages} hasNextPage={pagination.hasNextPage} hasPreviousPage={pagination.hasPreviousPage} onPageChange={changePage} onPageSizeChange={changePageSize} disabled={busy||loading}/></div>
   {message&&<div className="mt-4 rounded-xl border bg-slate-50 p-3 text-sm font-bold">{message}</div>}
  </div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Lifecycle control</h2><div className="mt-4 flex flex-wrap items-center gap-2 text-xs font-bold">{flow.map(([a,b],n)=><span key={a} className="flex items-center gap-2"><span className="rounded-full border px-3 py-1.5">{a}</span><span>→</span>{n===flow.length-1?<span className="rounded-full border px-3 py-1.5">{b}</span>:null}</span>)}</div><p className="mt-3 text-xs text-slate-500">The frozen runtime represents customer-eligible question content with QuestionStatus.PUBLISHED. ACTIVATE is therefore an explicit governed operation recorded in the audit trail without changing measurement semantics.</p></div>
  {selected&&inspected&&<div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="text-lg font-black">Content inspector</h2><p className="text-sm text-slate-500">{inspected.current.code} · {inspected.current.version}</p></div><button onClick={()=>{setSelected(null);setInspected(null)}} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Close</button></div><div className="mt-4 grid gap-4 md:grid-cols-3"><div><div className="text-xs font-bold text-slate-500">Status</div><div className="mt-1 font-bold">{inspected.current.status}</div></div><div><div className="text-xs font-bold text-slate-500">Mapping</div><div className="mt-1 font-bold">{inspected.current.mappingStatus}</div></div><div><div className="text-xs font-bold text-slate-500">Taxonomy Node</div><div className="mt-1 font-bold">{inspected.current.taxonomyNodeCode??"—"}</div></div><div><div className="text-xs font-bold text-slate-500">Validation</div><div className="mt-1 font-bold">{inspected.validationErrors.length?"Blocked":"Ready"}</div></div></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">{inspected.current.text}</p><h3 className="mt-5 font-black">Version history</h3><div className="mt-2 space-y-2">{inspected.versions.map((v:any)=><div key={v.id} className="flex justify-between rounded-xl border p-3 text-xs"><span className="font-mono">{v.version}</span><span>{v.status}</span><span>{new Date(v.updatedAt).toLocaleString()}</span></div>)}</div><h3 className="mt-5 font-black">Audit trail</h3><div className="mt-2 space-y-2">{inspected.audits.map((a:any)=><div key={a.id} className="rounded-xl border p-3 text-xs"><b>{a.action}</b> · {a.fromStatus||"—"} → {a.toStatus||"—"} · {new Date(a.createdAt).toLocaleString()}</div>)}</div></div>}
 </div>
}
