"use client";

import { useEffect, useState } from "react";

type C={id:string;code:string;name:string;assessmentType:string;description:string|null;versionId:string;version:string;questionBankVersion:string;taxonomyVersion:string;scoringVersion:string;selectionAlgorithmVersion:string;questionCount:number;status:string};
type V={id:string;version:string;questionBankVersion:string;taxonomyVersion:string;scoringVersion:string;selectionAlgorithmVersion:string;questionCount:number;status:string;createdAt:string;updatedAt:string};

const empty={code:"",name:"",assessmentType:"RIASEC",description:"",questionBankVersion:"QB_RUNTIME",taxonomyVersion:"TAXONOMY_RUNTIME",scoringVersion:"RIASEC_SCORE_V1",selectionAlgorithmVersion:"RIASEC_SELECTION_V1",questionCount:"60"};

export default function AssessmentConfigurationWorkspace({initial}:{initial:C[]}) {
 const [items,setItems]=useState(initial); const [selected,setSelected]=useState<C|null>(null);
 const [versions,setVersions]=useState<V[]>([]); const [mode,setMode]=useState<"create"|"edit"|null>(null);
 const [form,setForm]=useState({...empty}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 async function refresh(){const r=await fetch("/api/admin/assessment-config",{cache:"no-store"});const j=await r.json();if(j.ok)setItems(j.configurations)}
 async function inspect(c:C){setSelected(c);setMessage("");const r=await fetch(`/api/admin/assessment-config?id=${encodeURIComponent(c.id)}`,{cache:"no-store"});const j=await r.json();if(j.ok)setVersions(j.configuration.versions)}
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/assessment-config",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error?.code||"Action failed");setMessage("Saved.");await refresh();setMode(null);if(selected)await inspect({...selected, ...(j.version?{versionId:j.version.id,version:j.version.version,status:j.version.status}: {})})}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 function create(){setSelected(null);setMode("create");setForm({...empty})}
 function edit(c:C){setSelected(c);setMode("edit");setForm({code:c.code,name:c.name,assessmentType:c.assessmentType,description:c.description??"",questionBankVersion:c.questionBankVersion,taxonomyVersion:c.taxonomyVersion,scoringVersion:c.scoringVersion,selectionAlgorithmVersion:c.selectionAlgorithmVersion,questionCount:String(c.questionCount)})}
 return <div className="space-y-6">
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><b>Configuration safety.</b> This workspace manages assessment-instrument contracts separately from question content. Editing creates a new configuration version; historical versions are never overwritten. Activation is explicit.</div>
  <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Configurations</div><div className="mt-2 text-2xl font-black">{items.length}</div></div><div className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Active versions</div><div className="mt-2 text-2xl font-black">{items.filter(x=>x.status==="ACTIVE").length}</div></div><div className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Instrument boundary</div><div className="mt-2 font-bold">Content ≠ Configuration</div></div></div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Assessment configurations</h2><p className="text-sm text-slate-500">RIASEC · DISC · EQ · Cognitive plus commercial assessment types</p></div><button onClick={create} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">+ New configuration</button></div>
   <div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Type</th><th className="px-4 py-3">Configuration</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Question bank</th><th className="px-4 py-3">Taxonomy</th><th className="px-4 py-3">Scoring</th><th className="px-4 py-3">Selection</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead>
   <tbody className="divide-y">{items.map(c=><tr key={c.id} className="hover:bg-slate-50"><td className="px-4 py-4 font-bold">{c.assessmentType}</td><td className="px-4 py-4"><b>{c.name}</b><div className="font-mono text-xs text-slate-500">{c.code}</div></td><td className="px-4 py-4 font-mono text-xs">{c.version}</td><td className="px-4 py-4 font-mono text-xs">{c.questionBankVersion}</td><td className="px-4 py-4 font-mono text-xs">{c.taxonomyVersion}</td><td className="px-4 py-4 font-mono text-xs">{c.scoringVersion}</td><td className="px-4 py-4 font-mono text-xs">{c.selectionAlgorithmVersion}</td><td className="px-4 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{c.status}</span></td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>inspect(c)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Inspect</button><button onClick={()=>edit(c)} disabled={c.status==="ARCHIVED"} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold disabled:opacity-40">New version</button></div></td></tr>)}</tbody></table></div>
  </div>
  {selected&&<div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><div><div className="text-xs font-bold uppercase tracking-widest text-indigo-600">Configuration inspector</div><h2 className="mt-1 text-xl font-black">{selected.name} · {selected.assessmentType}</h2></div><button onClick={()=>setSelected(null)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Close</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold"><tr><th className="px-3 py-2">Version</th><th className="px-3 py-2">Question Bank</th><th className="px-3 py-2">Taxonomy</th><th className="px-3 py-2">Scoring</th><th className="px-3 py-2">Selection</th><th className="px-3 py-2">Count</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Action</th></tr></thead><tbody className="divide-y">{versions.map(v=><tr key={v.id}><td className="px-3 py-3 font-mono text-xs">{v.version}</td><td className="px-3 py-3 font-mono text-xs">{v.questionBankVersion}</td><td className="px-3 py-3 font-mono text-xs">{v.taxonomyVersion}</td><td className="px-3 py-3 font-mono text-xs">{v.scoringVersion}</td><td className="px-3 py-3 font-mono text-xs">{v.selectionAlgorithmVersion}</td><td className="px-3 py-3">{v.questionCount}</td><td className="px-3 py-3 font-bold">{v.status}</td><td className="px-3 py-3"><div className="flex gap-2">{v.status!=="ACTIVE"&&v.status!=="ARCHIVED"&&<button onClick={()=>act({action:"ACTIVATE",versionId:v.id})} className="rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-bold text-white">Activate</button>}{v.status!=="ACTIVE"&&v.status!=="ARCHIVED"&&<button onClick={()=>act({action:"ARCHIVE",versionId:v.id})} className="rounded-lg border border-rose-200 px-2.5 py-1.5 text-xs font-bold text-rose-700">Archive</button>}</div></td></tr>)}</tbody></table></div>{message&&<p className="mt-4 text-sm font-bold">{message}</p>}</div>}
  {mode&&<div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-black">{mode==="create"?"Create logical configuration":"Create configuration version"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">
   {mode==="create"&&<><label className="text-sm font-bold">Code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-bold">Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-bold">Assessment Type<select value={form.assessmentType} onChange={e=>setForm({...form,assessmentType:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2">{["FREE","PREMIUM","RIASEC","DISC","EQ","COGNITIVE"].map(x=><option key={x}>{x}</option>)}</select></label></>}
   {mode==="create"&&<label className="text-sm font-bold">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>}
   {[["Question Bank Version","questionBankVersion"],["Taxonomy Version","taxonomyVersion"],["Scoring Version","scoringVersion"],["Selection Algorithm Version","selectionAlgorithmVersion"]].map(([label,key])=><label key={key} className="text-sm font-bold">{label}<input value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>)}<label className="text-sm font-bold">Question Count<input type="number" min="1" value={form.questionCount} onChange={e=>setForm({...form,questionCount:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>
   </div><div className="mt-5 flex gap-2"><button disabled={busy} onClick={()=>act(mode==="create"?{action:"CREATE",...form,questionCount:Number(form.questionCount)}:{action:"EDIT",configurationId:selected?.id,...form,questionCount:Number(form.questionCount)})} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Save</button><button onClick={()=>setMode(null)} className="rounded-xl border px-4 py-2.5 text-sm font-bold">Cancel</button></div></div>}
 </div>
}
