"use client";
import { useState } from "react";

type RequestItem={id:string;userId:string|null;emailSnapshot:string;nameSnapshot:string|null;reason:string|null;status:"REQUESTED"|"PROCESSING"|"COMPLETED"|"REJECTED";requestedAt:string;processedAt:string|null;processingNotes:string|null};
export function DataDeletionAdmin({initialRequests}:{initialRequests:RequestItem[]}){
 const [items,setItems]=useState(initialRequests); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState("");
 async function process(item:RequestItem){ if(!window.confirm(`PROSES DATA DELETION\n\n${item.emailSnapshot}\n\nAkun akan dinonaktifkan, session dicabut, authentication artifacts dihapus, dan identity fields dianonimkan. Historical records tidak dihapus secara destruktif.\n\nLanjutkan?`)) return; setBusy(item.id); setMessage(""); try{const r=await fetch("/api/admin/data-deletion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId:item.id,confirmed:true})}); const b=await r.json(); if(!r.ok) throw new Error(b.error?.code||"DATA_DELETION_FAILED"); setItems((x)=>x.map((v)=>v.id===item.id?{...v,status:b.request.status,processedAt:b.request.processedAt,processingNotes:b.request.processingNotes}:v)); setMessage("Data deletion request processed and audited.");}catch(e){setMessage(e instanceof Error?e.message:"DATA_DELETION_FAILED");}finally{setBusy(null)}}
 return <><div className="mb-5 rounded-2xl border bg-slate-50 p-4 text-sm text-slate-700">{message||"Only process a request after verifying account ownership and the applicable retention requirement."}</div><div className="overflow-x-auto rounded-3xl border bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Request</th><th className="px-5 py-4">User</th><th className="px-5 py-4">Reason</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y">{items.map((item)=><tr key={item.id} className="align-top"><td className="px-5 py-4"><div className="font-mono text-xs font-bold">{item.id}</div><div className="mt-1 text-xs text-slate-500">{new Date(item.requestedAt).toLocaleString("id-ID")}</div></td><td className="px-5 py-4"><div className="font-black">{item.nameSnapshot||"—"}</div><div className="mt-1 text-xs text-slate-500">{item.emailSnapshot}</div><div className="mt-1 font-mono text-[10px] text-slate-400">{item.userId||"No matched account"}</div></td><td className="max-w-sm px-5 py-4 text-slate-600">{item.reason||"—"}</td><td className="px-5 py-4"><span className="rounded-full border px-2.5 py-1 text-xs font-black">{item.status}</span></td><td className="px-5 py-4">{item.status==="REQUESTED"?<button disabled={busy===item.id} onClick={()=>void process(item)} className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white disabled:opacity-50">{busy===item.id?"Processing…":"Process deletion"}</button>:<span className="text-xs text-slate-500">{item.processedAt?new Date(item.processedAt).toLocaleString("id-ID"):"—"}</span>}</td></tr>)}</tbody></table></div></>;
}
