import { prisma } from "../db/prisma";
import { hasFeatureAccess } from "../commercial/entitlement-service";
import { buildCrossTestProfile } from "../profile/engine-v1";
import type { CrossTestProfileInput } from "../profile/types";
import { buildIntegratedProfile } from "./interpretation/engine-v1";
import { rankMajors } from "./major-matching/engine-v1";
import { buildActionPlan } from "./action-plan/engine-v1";
import { buildV15Report } from "./report/engine-v1";

const TYPES=["RIASEC","DISC","EQ","COGNITIVE"] as const;
function normalize(a:{id:string;assessmentType:string;status:string;scoringVersion:string;result:{result:unknown}|null}):CrossTestProfileInput|null{if(a.status!=="COMPLETED"||!a.result)return null; const r=a.result.result as Record<string,unknown>; const key=a.assessmentType.toLowerCase(); const specific=r[key]; if(!specific||typeof specific!=="object")return null; const i=r.interpretation as Record<string,unknown>|undefined; return {result:{attemptId:a.id,assessmentType:a.assessmentType,scoringVersion:a.scoringVersion,status:a.status,interpretation:i?{contractVersion:String(i.contractVersion??"TEST_RESULT_V1"),interpretationVersion:String(i.interpretationVersion??"UNKNOWN"),status:String(i.status??"COMPLETE"),confidence:(i.confidence==="HIGH"||i.confidence==="MODERATE"||i.confidence==="LIMITED"?i.confidence:"LIMITED")} : undefined},testSpecific:specific};}
export async function generateV15Report(userId:string){if(!(await hasFeatureAccess(userId,"REPORT_ACCESS","ADVANCED_REPORT_V1")))throw new Error("REPORT_ACCESS_REQUIRED"); const attempts=await prisma.assessmentAttempt.findMany({where:{userId,status:"COMPLETED",assessmentType:{in:[...TYPES]}},orderBy:[{completedAt:"desc"},{updatedAt:"desc"}],select:{id:true,assessmentType:true,status:true,scoringVersion:true,completedAt:true,result:{select:{result:true}}}}); const latest=new Map<string,CrossTestProfileInput>(); for(const a of attempts){const k=a.assessmentType;if(!latest.has(k)){const n=normalize(a);if(n)latest.set(k,n);}} const inputs=[...latest.values()]; const profile=buildCrossTestProfile(inputs); const integrated=buildIntegratedProfile(profile); const signals=profile.domains.flatMap(d=>d.signals); const recommendations=rankMajors(integrated,signals); const actionPlan=buildActionPlan(integrated,recommendations); const resultVersions=inputs.map(i=>`${i.result.assessmentType}:${i.result.scoringVersion}:${i.result.interpretation?.contractVersion??"UNKNOWN"}`).sort(); const report=buildV15Report({resultVersions,profile:integrated,recommendations,actionPlan,signals}); const sourceFingerprint=JSON.stringify({attemptIds:inputs.map(i=>i.result.attemptId).sort(),resultVersions,interpretationVersion:report.interpretationVersion,majorKnowledgeVersion:report.majorKnowledgeVersion,majorMatchingVersion:report.majorMatchingVersion,actionPlanVersion:report.actionPlanVersion,templateVersion:report.templateVersion}); const existing=await prisma.v15Report.findUnique({where:{sourceFingerprint}}); if(existing) return {id:existing.id,report:existing.payload as typeof report}; const saved=await prisma.v15Report.create({data:{userId,status:report.status,sourceFingerprint,assessmentAttemptIds:inputs.map(i=>i.result.attemptId),resultVersions,interpretationVersion:report.interpretationVersion,majorKnowledgeVersion:report.majorKnowledgeVersion,majorMatchingVersion:report.majorMatchingVersion,actionPlanVersion:report.actionPlanVersion,templateVersion:report.templateVersion,payload:report}}); return {id:saved.id,report};}
