import fs from "node:fs";
import path from "node:path";
const ROOT = process.cwd();
const fail = (message: string): never => { throw new Error(`V8.2 check failed: ${message}`); };
const pass = (message: string) => console.log(`PASS: ${message}`);
const exists = (relative: string) => { if (!fs.existsSync(path.join(ROOT, relative))) fail(`required artifact missing: ${relative}`); };
const read = (relative: string) => fs.readFileSync(path.join(ROOT, relative), "utf8");
const assert = (condition: unknown, message: string) => { if (!condition) fail(message); };
console.log("=== READY SCORE V8.2 QUESTION & SCORING ARCHITECTURE CONTRACT GATE ===");
console.log("Scope      : Question model, response architecture, scoring adapters, result boundaries");
console.log("Protection : Architecture-only; no production measurement/scoring mutation");
const spec = "architecture/phase-8.2/ReadyScore_V8_2_Question_Scoring_Architecture.md";
const json = "data/assessment-audit/V8_2_QUESTION_SCORING_ARCHITECTURE.json";
const v81 = "data/assessment-audit/V8_1_MEASUREMENT_SPEC_LOCK.json";
exists(spec); exists(json); exists(v81);
const s = read(spec); const j = JSON.parse(read(json)) as any; const lock = JSON.parse(read(v81)) as any;
for (const marker of ["ReadyScore V8.2","No universal score","Historical question versions are immutable","Cognitive Adapter","EQ Adapter","DISC Adapter","RIASEC Adapter","Scoring Adapter Contract","V8.2 STATUS: LOCKED ARCHITECTURE"]) assert(s.includes(marker), `architecture marker missing: ${marker}`);
pass("V8.2 architecture specification is present");
assert(lock.version === "V8.1" && lock.status === "LOCKED", "V8.1 measurement lock is not present/locked"); pass("V8.1 measurement lock is present and locked");
assert(j.version === "V8.2" && j.status === "LOCKED", "V8.2 architecture status/version invalid"); pass("V8.2 architecture status is locked");
assert(j.implementation_status === "ARCHITECTURE_ONLY", "V8.2 implementation boundary invalid"); pass("V8.2 is architecture-only");
assert(j.global_rules?.no_database_migration === true, "V8.2 database migration prohibition missing"); pass("V8.2 declares no database migration");
assert(j.global_rules?.no_universal_score === true, "Global architecture rule represented: no_universal_score"); pass("Global architecture rule represented: no_universal_score");
assert(j.global_rules?.assessment_specific_response_models === true, "assessment-specific response model rule missing"); pass("Assessment-specific response model rule is locked");
assert(j.global_rules?.historical_question_versions_immutable === true, "historical question immutability rule missing"); pass("Historical question version immutability is locked");
assert(j.global_rules?.scoring_semantics_versioned === true, "scoring versioning rule missing"); pass("Scoring semantics versioning is locked");
const expected = { cognitive:["SINGLE_CHOICE","objective_keyed"], eq:["SCENARIO_SINGLE_CHOICE","situational_judgment"], disc:["SCENARIO_FORCED_CHOICE","one_most_representative_option"], riasec:["LIKERT_5_PREFERENCE","preference"] } as const;
for (const [name,[questionType,responseModel]] of Object.entries(expected)) { const item=j.assessments?.[name]; assert(item?.question_type===questionType && item?.response_model===responseModel, `${name} response architecture does not match V8.1`); pass(`${name} response model matches V8.1`); }
assert(j.assessments.cognitive.target_items===24 && j.assessments.cognitive.items_per_dimension===6, "Cognitive 24-item / 4x6 architecture invalid"); pass("Cognitive 24-item / 4×6 architecture is locked");
assert(j.assessments.cognitive.item_scoring.correct===1 && j.assessments.cognitive.item_scoring.incorrect===0, "Cognitive objective scoring invalid"); pass("Cognitive objective item scoring is locked");
assert(j.assessments.eq.target_items===24 && j.assessments.eq.items_per_dimension===6, "EQ 24-item / 4x6 architecture invalid"); pass("EQ 24-item / 4×6 architecture is locked");
assert(j.assessments.eq.key_values_finalized_in==="V8.4", "EQ final scoring key boundary missing"); pass("EQ keyed ordinal scoring is explicit without inventing final keys");
assert(j.assessments.disc.target_items===24 && j.assessments.disc.options_per_item===4, "DISC 24-item / 4-option architecture invalid"); pass("DISC 24-item / 4-option architecture is locked");
assert(j.assessments.disc.overall_rule==="profile only; no universal ability score", "DISC universal ability score prohibition invalid"); pass("DISC has no universal ability score");
assert(j.assessments.disc.global_positional_mapping_forbidden===true, "DISC global positional mapping prohibition missing"); pass("DISC global positional mapping is forbidden");
assert(j.assessments.riasec.target_items===60 && j.assessments.riasec.items_per_dimension===10, "RIASEC 60-item / 6x10 architecture invalid"); pass("RIASEC 60-item / 6×10 architecture is locked");
const pkg=JSON.parse(read("package.json")) as {scripts?:Record<string,string>}; assert(pkg.scripts?.["v8:2:gate"]==="tsx scripts/validate-v8-2-question-scoring-architecture.ts", "V8.2 gate script is not registered correctly"); pass("V8.2 gate script is registered");
assert(j.v8_2_scope?.database_migration===false && j.v8_2_scope?.production_measurement_mutation===false, "V8.2 scope protection flags invalid"); pass("V8.2 production/database protection is locked");
const migrationsDir=path.join(ROOT,"prisma/migrations"); if(fs.existsSync(migrationsDir)){const migrations=fs.readdirSync(migrationsDir); if(migrations.some(name=>name.toLowerCase().includes("v8.2"))) fail("V8.2 migration detected");} pass("No V8.2 database migration introduced");
console.log("V8.2 QUESTION & SCORING ARCHITECTURE CONTRACT GATE: PASS");
