import { MAJOR_KB_V1 } from "../../../data/v15/major-kb-v1";
import { V15_MAJOR_KB_VERSION, V15_MAJOR_MATCHING_VERSION, type IntegratedProfile, type MajorKnowledgeEntry, type MajorRecommendation } from "../types";
import type { ProfileSignal } from "../../profile/types";
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const sentenceJoin=(first:string,second:string)=>{const a=first.trim().replace(/[.!?]+$/,""); const b=second.trim(); if(/^perlu\b/i.test(b)) return `${a}; ${b}.`; const c=b?b.charAt(0).toUpperCase()+b.slice(1):b; return `${a}. ${c}${/[.!?]$/.test(c) ? "" : "."}`;};
function affinityScore(signals:ProfileSignal[], affinities:Partial<Record<string,number>>|undefined, sourceDomain:string){const relevant=signals.filter(s=>s.status==="AVAILABLE"&&s.score!==null&&s.domain===sourceDomain&&affinities?.[s.dimension]); if(!relevant.length)return {score:0,evidence:[] as ProfileSignal[]}; const weighted=relevant.map(s=>({s,w:affinities![s.dimension]??0})); const total=weighted.reduce((a,x)=>a+x.w,0); return {score:total?weighted.reduce((a,x)=>a+(x.s.score??0)*x.w,0)/total:0,evidence:relevant.sort((a,b)=>(b.score??0)-(a.score??0)).slice(0,3)};}
export function rankMajors(profile:IntegratedProfile, signals:ProfileSignal[], kb:readonly MajorKnowledgeEntry[]=MAJOR_KB_V1): MajorRecommendation[]{
 const results=kb.map(m=>{const r=affinityScore(signals,m.riaSecAffinity,"INTEREST"),d=affinityScore(signals,m.discAffinity,"BEHAVIOR"),c=affinityScore(signals,m.cognitiveAffinity,"ABILITY"),e=affinityScore(signals,m.eqConsiderations,"EMOTIONAL"); const components=[r,d,c,e].filter(x=>x.evidence.length); const score=components.length?components.reduce((a,x,i)=>a+x.score*[.35,.2,.3,.15][[r,d,c,e].indexOf(x)],0)/components.reduce((a,x,i)=>a+[.35,.2,.3,.15][[r,d,c,e].indexOf(x)],0):0; const evidence=[...r.evidence,...d.evidence,...c.evidence,...e.evidence].filter((s,i,a)=>a.findIndex(x=>x.signalId===s.signalId)===i); const coverage=Math.round((components.length/4)*100); const strong=score>=70; const fit=strong?"Pola bukti relatif kuat pada beberapa dimensi yang relevan.":score>=55?"Ada beberapa sinyal yang mendukung dan layak divalidasi melalui eksplorasi.":"Bukti saat ini masih terbatas; jurusan ini lebih tepat diperlakukan sebagai opsi eksplorasi."; const why=strong?`${m.explanationTemplates.positive[0].trim().replace(/[.!?]+$/g,"")}.`:sentenceJoin(fit,m.explanationTemplates.caution[0]); return {major:{id:m.id,name:m.name,category:m.category,description:m.description},rank:0,matchSignal:fit,whyItFits:why,supportingSignals:evidence.map(s=>({signalId:s.signalId,label:s.label,sourceTestType:s.sourceTestType,score:s.score})),cautionSignals:m.cautionSignals.slice(0,2),relatedCareers:m.relatedCareers,explorationActions:m.explorationActions,score:Math.round(clamp(score)*10)/10,evidenceCoverage:coverage};}).filter(x=>x.supportingSignals.length>0).sort((a,b)=>b.score-a.score||a.major.name.localeCompare(b.major.name));
 const selected=results.slice(0,7); return selected.map((x,i)=>({...x,rank:i+1}));
}
export const V15_MAJOR_MATCHING_METADATA={version:V15_MAJOR_MATCHING_VERSION,knowledgeBaseVersion:V15_MAJOR_KB_VERSION,formula:"weighted evidence: RIASEC 35%, DISC 20%, Cognitive 30%, EQ 15%; unavailable dimensions are excluded and evidence coverage is surfaced",deterministic:true};
